### ISSUE TITLE
$ref in path

### ISSUE THREAD

**Issue by ElliottBregni** [Dorthu/openapi3#9]
I see this is a TODO. Any progress or updates you could share with me?

**Comment by zeph** [comment]
i'm not sure if there is active development on this library... @ElliottBregni have u found alternatives?

**Comment by zeph** [comment]
is this what u meant @ElliottBregni ? 

cause it is exactly giving me trouble in parsing the [public Atlassian's swagger (yes, click me)](https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json)
![href](https://user-images.githubusercontent.com/209808/81582077-e3e1b000-93af-11ea-9d48-f72ea9ec813b.png)

```python
Traceback (most recent call last):
  File "action.IS-579.py", line 14, in <module>
    api = OpenAPI(spec)
  File "/home/gms/tmp/_HF/security-examples/atlassian/.p3/lib/python3.7/site-packages/openapi3/openapi.py", line 36, in __init__
    super(OpenAPI, self).__init__([], raw_document, self)
  File "/home/gms/tmp/_HF/security-examples/atlassian/.p3/lib/python3.7/site-packages/openapi3/object_base.py", line 46, in __init__
    self._parse_data()
  File "/home/gms/tmp/_HF/security-examples/atlassian/.p3/lib/python3.7/site-packages/openapi3/openapi.py", line 116, in _parse_data
    self.components   = self._get('components', ['Components'])
  File "/home/gms/tmp/_HF/security-examples/atlassian/.p3/lib/python3.7/site-packages/openapi3/object_base.py", line 171, in _get
    ret = python_type(self.path + [field], ret, self._root)
  File "/home/gms/tmp/_HF/security-examples/atlassian/.p3/lib/python3.7/site-packages/openapi3/object_base.py", line 46, in __init__
    self._parse_data()
  File "/home/gms/tmp/_HF/security-examples/atlassian/.p3/lib/python3.7/site-packages/openapi3/components.py", line 22, in _parse_data
    self.schemas         = self._get('schemas', ['Schema', 'Reference'], is_map=True)
  File "/home/gms/tmp/_HF/security-examples/atlassian/.p3/lib/python3.7/site-packages/openapi3/object_base.py", line 155, in _get
    ret = Map(self.path + [field], ret, object_types, self._root)
  File "/home/gms/tmp/_HF/security-examples/atlassian/.p3/lib/python3.7/site-packages/openapi3/object_base.py", line 451, in __init__
    element=self)
openapi3.errors.SpecError: Expected components.schemas.avatarUrls to be one of [['Schema', 'Reference']], but found {'description': 'The avatars of the user.', '$ref': '#/components/schemas/AvatarUrlsBean'}
```

**Comment by c7h** [comment]
I have a similar Issue. 

while [parsing this spec file](https://github.com/open5gs/open5gs/blob/831b29973feaed7ae7ca306de5c7dd1a1fa9c2d6/lib/sbi/support/20210629/modified/TS29510_Nnrf_NFManagement.yaml), I received this error: 

```
SpecError: Could not parse paths./nf-instances.get.parameters.6, expected to be one of [['Parameter', 'Reference']]
```

This is how the causing section looks like: 

```
{
    "name": "target-plmn-list",
    "in": "query",
    "description": "Id of the PLMN of the target NF",
    "content": {
        "application/json": {
            "schema": {
                "type": "array",
                "items": {
                    "$ref": "TS29571_CommonData.yaml#/components/schemas/PlmnId"
                },
                "minItems": 1
            }
        }
    }
}
```

It should be valid OAS3, right?

**Comment by chriswhite199** [comment]
@c7h - One issue i see with your spec is the use of reference items in another file. From what i can tell, openapi3 (this library) doesn't follow file $refs and can only handle everything in the same file (there don't appear to be any additional calls to yaml.load_safe other than in `__main__.py`

**Comment by chriswhite199** [comment]
@zeph - This is a similar issue to #61, in that `general.py::Reference.can_parse()` doesn't like anything other than a single $ref child to a property, and in the Atlassian case, they use this pattern (`allOf[0].$ref`):

```json
    "issueType": {
      "description": "The type of the linked issue.",
      "readOnly": true,
      "allOf": [
        {
          "$ref": "#/components/schemas/IssueTypeDetails"
        }
      ]
    }
```

**Comment by Dorthu** [comment]
@c7h the above is true - at present this library does not load additional files when following $refs.  

Additionally, the [Parameter object]() has not `content`; it should instead have a `schema` that describes what value goes there:

```
{
    "name": "target-plmn-list",
    "in": "query",
    "description": "Id of the PLMN of the target NF",
    "schema": {
        "type": "array",
        "items": {
            "$ref": "TS29571_CommonData.yaml#/components/schemas/PlmnId"
        },
        "minItems": 1
    }
}
```

Making this change results in the following (expected) error:

```
ReferenceResolutionError: Invalid reference path TS29571_CommonData.yaml#/components/schemas/PlmnId
```
